### ISSUE TITLE
CartService: First item in list is accessed regardless of size

### ISSUE THREAD

**Issue by DeimosA** [Shamzaa/TDT4242-Group2#81]
shopping-cart.service.ts:38
"Fetching the first element of an array regardless of its size puts burden on outside
code, and should generally be avoided if it may fail. The issue could be avoided by
using forEach, which will succeed regardless of the size of the array."

**Comment by arwassa** [comment]
the only thing the filtering does it to try to find a shopping cart item that satisfies a given productId, I don't see how forEach would be relevant here. Using Array.filter is however less readable than using Array.find so it shoud be replaced.
